%bcond check 1

Name:           microvisor
Version:        0.1.1
Release:        1%{?buildtag}%{?dist}
Summary:        Headless SELinux protection profile manager

# The Microvisor sources are MIT. The remaining expressions are generated by
# %%cargo_license_summary for Rust crates statically linked into the binary.
SourceLicense:  MIT
License:        MIT AND (Apache-2.0 OR MIT) AND ((Apache-2.0 WITH LLVM-exception) OR Apache-2.0 OR MIT) AND ((Apache-2.0 OR MIT) AND BSD-3-Clause) AND (BSD-2-Clause OR Apache-2.0 OR MIT) AND ((MIT OR Apache-2.0) AND Unicode-3.0) AND (MIT OR Unlicense)
URL:            https://github.com/nexryai/microvisor

Source0:        %{name}-%{version}.tar.xz
Source1:        %{name}-%{version}-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  cargo >= 1.85
BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  rust >= 1.85

Requires:       checkpolicy
Requires:       libselinux-utils >= 3.6
Requires:       m4
Requires:       policycoreutils >= 3.6
Requires:       policycoreutils-python-utils >= 3.6
Requires:       /usr/share/selinux/devel/include/build.conf

%description
Microvisor is a headless root command-line tool that reconciles versioned YAML
profiles into per-application SELinux policy modules, file-context rules, and
labels. It is intended for workstations and servers with SELinux Enforcing.

This package is experimental and Fedora-focused. Generated policies must be
reviewed before they are used to protect production data.

%prep
%autosetup -a1
%cargo_prep -v vendor

%build
export CARGO_HOME="$PWD/.cargo"
export CARGO_NET_OFFLINE=true
export RUSTFLAGS="%{build_rustflags}"

cargo build --release --locked

%cargo_license_summary
%{cargo_license} > LICENSE.dependencies
%cargo_vendor_manifest

%install
install -Dpm 0755 target/release/microvisor %{buildroot}%{_bindir}/microvisor
install -Dpm 0644 data/microvisor.8 %{buildroot}%{_mandir}/man8/microvisor.8
install -Dpm 0600 data/microvisor.yml %{buildroot}%{_sysconfdir}/microvisor.yml

%if %{with check}
%check
export CARGO_HOME="$PWD/.cargo"
export CARGO_NET_OFFLINE=true
export RUSTFLAGS="%{build_rustflags}"

cargo test --release --locked
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc PLANS.md
%{_bindir}/microvisor
%{_mandir}/man8/microvisor.8*
%config(noreplace) %attr(0600,root,root) %{_sysconfdir}/microvisor.yml

%changelog
* Tue Aug 11 2026 Nexryai <nexryai@users.noreply.github.com> - 0.1.0-1
- Replace the desktop application and Polkit helper with a root YAML CLI
