%bcond check 1

Name:           microvisor
Version:        0.1.0
Release:        1%{?buildtag}%{?dist}
Summary:        GNOME application for protecting application data with SELinux

# The Microvisor sources are MIT. The remaining expressions are the output of
# %%cargo_license_summary for Rust crates statically linked into the binaries:
#
# Apache-2.0 OR MIT
# Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
# MPL-2.0
# Unlicense OR MIT
SourceLicense:  MIT
License:        MIT AND (Apache-2.0 OR MIT) AND ((Apache-2.0 WITH LLVM-exception) OR Apache-2.0 OR MIT) AND MPL-2.0 AND (MIT OR Unlicense)
URL:            https://github.com/nexryai/microvisor

# .copr/Makefile creates both archives from the selected SCM revision.
Source0:        %{name}-%{version}.tar.xz
Source1:        %{name}-%{version}-vendor.tar.xz

ExclusiveArch:  %{rust_arches}

BuildRequires:  appstream
BuildRequires:  cargo >= 1.85
BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  desktop-file-utils
BuildRequires:  meson >= 1.3
BuildRequires:  ninja-build
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gtk4) >= 4.18
BuildRequires:  pkgconfig(libadwaita-1) >= 1.8
BuildRequires:  rust >= 1.85
BuildRequires:  /usr/bin/glib-compile-resources

# The privileged helper invokes these programs through an allowlisted argv.
Requires:       checkpolicy
Requires:       libselinux-utils >= 3.6
Requires:       make
Requires:       policycoreutils >= 3.6
Requires:       policycoreutils-python-utils >= 3.6
Requires:       polkit
Requires:       /usr/share/selinux/devel/Makefile

%description
Microvisor is a GNOME application for generating and applying per-application
SELinux protection profiles. The graphical process remains unprivileged;
policy installation and file relabeling are performed by a small helper after
Polkit authentication.

This package is an experimental, Fedora-focused implementation. Generated
policies should be reviewed before they are used to protect production data.

%prep
%autosetup -a1
%cargo_prep -v vendor

%build
# Meson invokes Cargo from its build directory. Point Cargo back to the
# source-side configuration generated by %%cargo_prep so it uses only Source1.
export CARGO_HOME="$PWD/.cargo"
export CARGO_NET_OFFLINE=true
export RUSTFLAGS="%{build_rustflags}"

%meson
%meson_build

%cargo_license_summary
%{cargo_license} > LICENSE.dependencies
%cargo_vendor_manifest

%install
%meson_install

%if %{with check}
%check
export CARGO_HOME="$PWD/.cargo"
export CARGO_NET_OFFLINE=true
export RUSTFLAGS="%{build_rustflags}"

%cargo_test -n
desktop-file-validate \
    %{buildroot}%{_datadir}/applications/me.nexryai.microvisor.desktop
appstreamcli validate --no-net \
    %{buildroot}%{_metainfodir}/me.nexryai.microvisor.metainfo.xml
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc PLANS.md
%{_bindir}/microvisor
%{_libexecdir}/microvisor-helper
%{_datadir}/applications/me.nexryai.microvisor.desktop
%{_datadir}/icons/hicolor/scalable/apps/me.nexryai.microvisor.svg
%{_datadir}/icons/hicolor/symbolic/apps/me.nexryai.microvisor-symbolic.svg
%{_datadir}/polkit-1/actions/me.nexryai.microvisor.policy
%{_metainfodir}/me.nexryai.microvisor.metainfo.xml

%changelog
* Wed Jul 29 2026 Nexryai <nexryai@users.noreply.github.com> - 0.1.0-1
- Initial Copr package
