use crate::model::ProtectionProfile;
use anyhow::{Context, Result, bail};
use std::path::{Component, Path};

// Cover every SELinux filesystem object class. Fedora's unconfined policy grants access through
// broad file-type attributes, so omitting even device-node classes leaves a residual allow rule.
const TYPE_PERMISSIONS: &[(&str, &str)] = &[
    ("dir", "all"),
    ("file", "all"),
    ("lnk_file", "all"),
    ("chr_file", "all"),
    ("blk_file", "all"),
    ("sock_file", "all"),
    ("fifo_file", "all"),
];

pub fn validate_profile(profile: &ProtectionProfile) -> Result<()> {
    let name = profile.name.trim();
    if name.is_empty() {
        bail!("Application name is required");
    }
    if name.chars().count() > 128 {
        bail!("Application name must not exceed 128 characters");
    }
    if name.chars().any(char::is_control) {
        bail!("Application name contains control characters");
    }

    validate_absolute_path(&profile.executable, "executable")?;
    if profile.data_directories.is_empty() {
        bail!("At least one protected directory is required");
    }

    let mut directories = profile.data_directories.clone();
    directories.sort();
    if directories.windows(2).any(|pair| pair[0] == pair[1]) {
        bail!("Protected directories must not contain duplicates");
    }

    for directory in &profile.data_directories {
        validate_absolute_path(directory, "protected directory")?;
        // This inexpensive UI-side check is repeated after canonicalization in the helper. The
        // helper-side result is authoritative because the GUI is not a security boundary.
        if normal_component_count(directory) < 3 {
            bail!(
                "{} is too broad to protect safely; select an application-specific subdirectory",
                directory.display()
            );
        }
    }

    validate_selinux_identifier(&profile.launch_domain).context("Invalid launch domain")?;
    if !profile.launch_domain.ends_with("_t") {
        bail!("Launch domain must end with '_t'");
    }
    validate_selinux_identifier(&profile.launch_role).context("Invalid launch role")?;
    if !profile.launch_role.ends_with("_r") {
        bail!("Launch role must end with '_r'");
    }
    Ok(())
}

fn validate_absolute_path(path: &Path, label: &str) -> Result<()> {
    if !path.is_absolute() {
        bail!("The {label} path must be absolute");
    }
    if path == Path::new("/") {
        bail!("The filesystem root cannot be used as a {label}");
    }
    let value = path
        .to_str()
        .with_context(|| format!("The {label} path must be valid UTF-8"))?;
    if value.chars().any(char::is_control) {
        bail!("The {label} path contains control characters");
    }
    Ok(())
}

fn normal_component_count(path: &Path) -> usize {
    path.components()
        .filter(|component| matches!(component, Component::Normal(_)))
        .count()
}

pub fn validate_selinux_identifier(value: &str) -> Result<()> {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        bail!("SELinux identifier cannot be empty");
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        bail!("SELinux identifier must start with a letter or underscore");
    }
    if !chars.all(|character| character.is_ascii_alphanumeric() || character == '_') {
        bail!("SELinux identifier contains unsupported characters");
    }
    Ok(())
}

pub fn render_type_enforcement(profile: &ProtectionProfile) -> Result<String> {
    validate_profile(profile)?;
    let ids = profile.identifiers();

    Ok(format!(
        r#"policy_module({module}, 1.0)

# Generated by Microvisor. Manual changes will be overwritten.
gen_require(`
    type {launch_domain};
    role {launch_role};
')

type {app_type};
type {exec_type};
application_domain({app_type}, {exec_type})

# Keep the protected application compatible with an ordinary desktop session.
# The companion CIL module subtracts access to {data_type} from every other type.
unconfined_domain({app_type})
domtrans_pattern({launch_domain}, {exec_type}, {app_type})
role {launch_role} types {app_type};

type {data_type};
files_type({data_type})

manage_dirs_pattern({app_type}, {data_type}, {data_type})
manage_files_pattern({app_type}, {data_type}, {data_type})
manage_lnk_files_pattern({app_type}, {data_type}, {data_type})
allow {app_type} {data_type}:fifo_file manage_fifo_file_perms;
allow {app_type} {data_type}:sock_file manage_sock_file_perms;
"#,
        module = ids.module,
        launch_domain = profile.launch_domain,
        launch_role = profile.launch_role,
        app_type = ids.app_type,
        exec_type = ids.exec_type,
        data_type = ids.data_type,
    ))
}

pub fn render_deny_cil(profile: &ProtectionProfile) -> Result<String> {
    validate_profile(profile)?;
    let ids = profile.identifiers();
    // The complement is the confinement mechanism: every subject type except the protected
    // application is placed in the denied attribute. Do not replace this with a fixed allowlist
    // without reassessing how newly installed SELinux types can access protected data.
    let mut output = format!(
        r#"; Generated by Microvisor. Manual changes will be overwritten.
(typeattribute {allowed})
(typeattributeset {allowed} ({app_type}))

(typeattribute {denied})
(typeattributeset {denied} (not ({allowed})))

"#,
        allowed = ids.allowed_attribute,
        denied = ids.denied_attribute,
        app_type = ids.app_type,
    );

    for (class, permission) in TYPE_PERMISSIONS {
        output.push_str(&format!(
            "(deny {} {} ({} ({})))\n",
            ids.denied_attribute, ids.data_type, class, permission
        ));
    }

    if profile.block_ptrace {
        output.push_str(&format!(
            "\n(deny {} {} (process (ptrace)))\n",
            ids.denied_attribute, ids.app_type
        ));
    }
    if profile.block_fd_use {
        output.push_str(&format!(
            "(deny {} {} (fd (use)))\n",
            ids.denied_attribute, ids.app_type
        ));
    }

    Ok(output)
}

pub fn render_preview(profile: &ProtectionProfile) -> Result<String> {
    let ids = profile.identifiers();
    let te = render_type_enforcement(profile)?;
    let cil = render_deny_cil(profile)?;
    let executable = selinux_path_regex(&profile.executable)?;

    let mut operations = format!(
        "# File-context operations\nsemanage fcontext -a -f f -t {} {}\nrestorecon -v {}\n",
        ids.exec_type,
        shell_quote(&executable),
        shell_quote(&profile.executable.to_string_lossy())
    );

    for directory in &profile.data_directories {
        let regex = recursive_directory_regex(directory)?;
        operations.push_str(&format!(
            "semanage fcontext -a -t {} {}\nrestorecon -RFv {}\n",
            ids.data_type,
            shell_quote(&regex),
            shell_quote(&directory.to_string_lossy())
        ));
    }

    Ok(format!(
        "# {}.te\n{}\n# {}.cil\n{}\n{}",
        ids.module, te, ids.deny_module, cil, operations
    ))
}

pub fn recursive_directory_regex(path: &Path) -> Result<String> {
    Ok(format!("{}(/.*)?", selinux_path_regex(path)?))
}

pub fn selinux_path_regex(path: &Path) -> Result<String> {
    let value = path
        .to_str()
        .context("SELinux file-context paths must be valid UTF-8")?;
    let mut escaped = String::with_capacity(value.len());

    // semanage interprets file-context paths as regular expressions. Escape metacharacters so a
    // literal user-selected path cannot broaden the rule to neighboring files or directories.
    for character in value.chars() {
        if matches!(
            character,
            '.' | '^' | '$' | '*' | '+' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '|' | '\\'
        ) {
            escaped.push('\\');
        }
        escaped.push(character);
    }

    Ok(escaped)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}
